car:
  radius: 25
  speed: 100.0
  work_width: 32

task:
  type: 2
  obstacles:
    - - {x: 0.0, y: 0.0}
      - {x: 50.0, y: 50.0}
    - - {x: 100.0, y: 30.0}
      - {x: 150.0, y: 80.0}
  destinations:
    - {x: -30.0, y: 00.0}
    - {x: 60.0, y: 120.0}
    - {x: 80.0, y: -20.0}
